### ISSUE TITLE
Get tags from json

### ISSUE THREAD

**Issue by mcmegavolt** [archit/jqcloud-rails#2]
What about providing some documentaion about getting tags from json in javascript?
Can you do this?
Thnks for the gem!

**Comment by archit** [comment]
@mcmegavolt , I'd refer you to the jQCloud documentation for that @ https://github.com/lucaong/jQCloud. The first example shows you how to feed a JSON object with tag frequencies "into" a jQCloud. 

If you do have any ideas for rails generators in mind, do let me know. Bonus points if you can cook up a pull request. 

This gem is lacking some generators to get the developer, up and running quickly.

**Comment by cmdalbem** [comment]
@archit I'm interested in doing the same, but I can't find the JSON example you mentioned in the link you provided.
